//########################################
//# This page contains score data, timing data and the media file path. Save it as a text file in
//# the same folder as abcweb.html. Abcweb preloads score and media when it is opened with the
//# file name as parameter in the url, for example: http://your.domain.org/abcweb.html?file_name
//# Also works locally with file:///path/to/abcweb.html?file_name
//# **** You have to correct the path to the media file below! (media_file="...";) ****
//########################################
//#
media_file = "I Walk The Line - Johnny Cash (mod).mp3";
offset_js = 0.00;
opt = {"jump":0,"no_menu":0,"repufld":0,"noplyr":0,"nocsr":0,"media_height":"","btns":1,"ipadr":"","mstr":0,"autscl":0,"ctrmed":0,"ctrnot":0,"lncsr":0,"opacity":0.2,"synbox":0,"speed":1,"top_margin":0,"yubvid":"","nomed":0,"delay":0,"repskip":0,"spdctl":0,"lopctl":false,"metro":0,"btime":-1,"etime":0};
lpRec = {"loopBtn":1,"loopStart":0,"loopEnd":140};
times_arr = [[0.00,3.70,6.00,8.30,10.60,12.90,15.20,17.50,19.80,22.10],
[22.10,24.40,26.60,28.70,31.00,33.30,35.60,37.90,40.20,42.28,44.48],
[44.48,46.64,48.90,51.16,53.52,55.88,58.24,60.40,62.36,64.62,66.88],
[66.88,69.14,71.40,73.65,75.91,78.27,80.43,82.69,84.95,87.21,89.47],
[89.47,91.83,94.09,96.25,98.41,100.57,102.73,104.99,107.25,109.50,111.76],
[111.76,114.02,116.28,118.54,120.80,123.06,125.32,127.58,129.84,132.10,134.36],
[134.36,136.62,138.98,141.24,143.49,145.85,147.91,150.17,152.53,154.79,157.05],
[157.05,161.31]];
abc_arr = ["X:1",
"T:I walk the line",
"%%scale 0.83",
"%%score 1 [ 2 3 ]",
"L:1/4",
"M:4/4",
"I:linebreak $",
"K:Bb",
"V:1 bass nm=\"Bass\" snm=\"B.\"",
"L:1/8",
"V:2 treble-8 nm=\"Electric Guitar\" snm=\"El. Guit.\"",
"V:3 bass nm=\"Electric Bass\" snm=\"El. B.\"",
"V:1",
" z8 |\"Bb\" z8 |\"Eb\" z8 |\"Bb\" z8 |\"F\" z8 |$\"C\" z8 |\"F\" z8 | F,8- | F,8 | z4 z F, =E,F, ||$ %10",
"w: |||||||Mm|_|I keep a|",
"\"C\" G,2 G,2 G,B,A,G, |\"F\" F,4- F,F,=E,F, |\"C\" G,2 G,2 G,B,A,G, |$\"F\" F,4- F,F,G,A, | %14",
"w: close watch on this heart of|mine _ I keep my|eyes wide o- pen all the|time _ I keep the|",
"\"Bb\" B,2 B,2 B,DCB, |\"F\" A,4- A,F,=E,D, |\"C\" C,4- C,G,F,=E, |$\"F\" F,8 |\"Bb\" z8 | B,,8- | B,,8 | %21",
"w: ends up for the tie that|binds _ Be- cause you're|mine _ I walk the|line||Mm|_|",
" z4 z B,, A,,B,, ||$\"F\" C,C, C,C, C,E,D,C, |\"Bb\" B,,4- B,,B,,A,,B,, |\"F\" C,3 C, C,E,D,C, |$ %25",
"w: I find it|ve- ry ve- ry ea- sy to be|true _ I find my-|self a- lone when each day's|",
"\"Bb\" B,,4- B,,B,,C,D, |\"Eb\" E,3 E, E,G,F,E, |\"Bb\" D,4- D,B,,A,,G,, |\"F\" F,,4- F,,C,B,,A,, |$ %29",
"w: trough _ Yes I'll ad-|mit that I'm a fool for|you * Be- cause you're|mine _ I walk the|",
"\"Bb\" B,,8 |\"Eb\" z8 | E,8- | E,8 | z4 z E, D,E, ||$\"Bb\" F,2 F,2 F,_A,G,F, |\"Eb\" E,4- E,E,D,E, | %36",
"w: line||Mm|_|As sure as|night is dark and day is|light _ I keep you|",
"\"Bb\" F,2 F,2 F,_A,G,F, |$\"Eb\" E,4- E,E,F,G, |\"Ab\" _A,2 A,2 A,CB,A, |\"Eb\" G,4- G,E,D,C, |$ %40",
"w: on my mind both day and|night _ And happ- i-|ness I've know proves that is's|right _ Be- cause you're|",
"\"Bb\" B,,4- B,,F,E,D, |\"Eb\" E,8 |\"Bb\" z8 | B,,8- | B,,8 | z4 z B,, A,,B,, ||$\"F\" C,3 C, C,E,D,C, | %47",
"w: mine _ I walk the|line||Mm|_|You've got a|way to keep me on your|",
"\"Bb\" B,,4- B,,B,,A,,B,, |\"F\" C,3 C, C,E,D,C, |$\"Bb\" B,,4- B,,B,,C,D, |\"Eb\" E,E,E,E, E,G,F,E, | %51",
"w: side _ You give me|cause for love that i can't|hide _ For you I|know I'd e- ven try to turn the|",
"\"Bb\" D,4- D,B,,A,,G,, |$\"F\" F,,4- F,,C,B,,A,, |\"Bb\" B,,8 |\"F\" z8 | F,,8- | F,,8 | %57",
"w: tide _ Be- cause you're|mine _ I walk the|line||Mm|_|",
" z4!8vb(! z F,, =E,,F,, ||$\"C\" G,,2 G,,2 G,,B,,A,,G,, |\"F\" F,,4- F,,F,,=E,,F,, | %60",
"w: I keep a|close watch on this heart of|mine _ I keep my|",
"\"C\" G,,2 G,,2 G,,B,,A,,G,, |$\"F\" F,,4- F,,F,,G,,A,, |\"Bb\" B,,2 B,,2 B,,D,C,B,, | %63",
"w: eyes wide o- pen all the|time _ I keep the|ends up for the tie that|",
"\"F\" A,,4- A,,F,,=E,,D,, |\"C\" C,,4- C,,G,,F,,=E,, |$\"F\" F,,8 | z8!8vb)! | F,8- | F,8 | z8 |] %70",
"w: binds _ Be- cause you're|mine _ I walk the|line||Mm|_||",
"V:2",
" z2 z/ F,/ G,/A,/ | B, F, B,/B,/ C/D/ | E B, E/E/ D/C/ | B, F B,/B,/ A,/G,/ | F, C C/F,/G,/F,/ |$ %5",
" C =E C/B,/A,/G,/ | F, C F, C | F, C F, C | F, C F, C | F, C F, C ||$ C G C G | F, C F, C | %12",
" C G C G |$ F, C F,/F,/ G,/A,/ | B, F B, F | F, C F, C | C G C G |$ F, C F,/F,/G,/A,/ | %18",
" B, F, B, F, | B, F, B, F, | B, F, B, F, | B, F, B, F, ||$ F, C F, C | B, F, B, F, | F, C F, C |$ %25",
" B, F, B,/B,/C/D/ | E B, E B, | B, F B, F | F, C F, C |$ B, F B,/B,/C/D/ | E B, E B, | E B, E B, | %32",
" E B, E B, | E B, E B, ||$ B, F B, F | E B, E B, | B, F, B, F |$ E B, E/E/F/G/ | _A E A E | %39",
" E B E B |$ B, F B, F | E B, E/B,/D/C/ | B, F B, F | B, F B, F | B, F B, F | B, F B, F ||$ %46",
" F, C F, C | B, F B, F | F, C F, C |$ B, F, B,/B,/C/D/ | E B, E B, | F B, F B, |$ F, C F, C | %53",
" B, F B,/B,/A,/G,/ | F, C F, C | F, C F, C | F, C F, C | F, C F, C ||$ C G C G | F, C F, C | %60",
" C G C G |$ F, C F,/F,/ G,/A,/ | B, F, B, F, | F, C F, C | C G C G |$ F, C F, C | F, C F, C | %67",
" F, C F, C | F, C F, C | F,4 |] %70",
"V:3",
" z4 | B,,, F,,, B,,,2 | E,, B,,, E,,2 | B,,, F,, B,,,2 | F,,, C,, F,,,2 |$ C,, G,,, C,,2 | %6",
" F,,, C,, F,,, C,, | F,,, C,, F,,, C,, | F,,, C,, F,,, C,, | F,,, C,, F,,, C,, ||$ %10",
" C,, G,, C,, G,, | F,,, C,, F,,, C,, | C,, G,, C,, G,, |$ F,,, C,, F,,,2 | B,,, F,, B,,, F,, | %15",
" F,,, C,, F,,, C,, | C,, G,, C,, G,, |$ F,,, C,, F,,,2 | B,,, F,,, B,,, F,,, | %19",
" B,,, F,,, B,,, F,,, | B,,, F,,, B,,, F,,, | B,,, F,,, B,,, F,,, ||$ F,,, C,, F,,, C,, | %23",
" B,,, F,,, B,,, F,,, | F,,, C,, F,,, C,, |$ B,,, F,,, B,,,2 | E,, B,,, E,, B,,, | %27",
" B,,, F,, B,,, F,, | F,,, C,, F,,, C,, |$ B,,, F,, B,,,2 | E,, B,,, E,, B,,, | E,, B,,, E,, B,,, | %32",
" E,, B,,, E,, B,,, | E,, B,,, E,, B,,, ||$ B,,, F,, B,,, F,, | E,, B,,, E,, B,,, | %36",
" B,,, F,,, B,,, F,, |$ E,, B,,, E,,2 | _A,,, E,, A,,, E,, | E,, B,, E,, B,, |$ B,,, F,, B,,, F,, | %41",
" E,, B,,, E,,2 | B,,, F,, B,,, F,, | B,,, F,, B,,, F,, | B,,, F,, B,,, F,, | B,,, F,, B,,, F,, ||$ %46",
" F,,, C,, F,,, C,, | B,,, F,, B,,, F,, | F,,, C,, F,,, C,, |$ B,,, F,,, B,,,2 | E,, B,,, E,, B,,, | %51",
" F,, B,,, F,, B,,, |$ F,,, C,, F,,, C,, | B,,, F,, B,,,2 | F,,, C,, F,,, C,, | F,,, C,, F,,, C,, | %56",
" F,,, C,, F,,, C,, | F,,, C,, F,,, C,, ||$ C,, G,, C,, G,, | F,,, C,, F,,, C,, | C,, G,, C,, G,, |$ %61",
" F,,, C,, F,,,2 | B,,, F,,, B,,, F,,, | F,,, C,, F,,, C,, | C,, G,, C,, G,, |$ F,,, C,, F,,, C,, | %66",
" F,,, C,, F,,, C,, | F,,, C,, F,,, C,, | F,,, C,, F,,, C,, | F,,,4 |] %70",
""];
abc_enc = [];
